name: praxis_developer_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State management
  flutter_bloc: ^8.1.5

  #Compare Dart objects
  equatable: ^2.0.5

  #Service Locator and Singletons
  get_it: ^7.7.0

  #DateFormat
  intl: ^0.19.0

  #Make request to API
  retrofit: ^4.1.0

  #Dio
  dio: ^5.4.3+1

  #For colors selection
  multi_dropdown: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
